# -*- coding: utf-8 -*-
"""best_rf_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jarNRy3KRP0G0uqT12Fh64GQFmFb7ktU
"""

import pickle

# Load the pickle file to verify
with open('best_rf_model.pkl', 'rb') as file:
    model = pickle.load(file)

print("Model loaded successfully!")