name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Service Principal credentials

    # Step 3: Build Docker image (Optional if Dockerfile is already in your repository)
    - name: Build Docker image
      run: |
        docker build -t abishekudhay.azurecr.io/bangalore-house-price-prediction:latest .

    # Step 4: Push Docker image to ACR
    - name: Push Docker image to ACR
      run: |
        docker login abishekudhay.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
        docker push abishekudhay.azurecr.io/bangalore-house-price-prediction:latest

    # Step 5: Deploy Docker container to Azure Web App Slot (Staging)
    - name: Deploy Docker container to Azure Web App Staging Slot
      uses: azure/webapps-container-deploy@v2
      with:
        app-name: 'bangalore-house-price-prediction-p'  # Name of the App Service (without the slot part)
        slot-name: 'staging'  # Slot name for staging
        image: 'abishekudhay.azurecr.io/bangalore-house-price-prediction:latest'  # Docker image to deploy
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Publish profile for the Azure Web App

