name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Change to your default branch if not `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Match the Python version your app requires

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 3: Deploy to Azure App Service Slot
    - name: Deploy to Azure WebApp Slot
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Bangalore-house-Price-Prediction'  # Replace with your App Service name
        slot-name: 'bwhuc7bxe2atecca'                # Update to your specific slot name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
