name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

<<<<<<< HEAD
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=." >> $GITHUB_ENV

=======
>>>>>>> e95f9513855788517b6248319dbbc561bb5ad6a1
    - name: Run Tests
      run: |
        pytest tests/
